Ethan replaceplaceholder
ucsb-cs156-f22/team03-f22-5pm-1 pull request #56
Opened 2022-11-11 22:30 UTC by ethanlee556

Close #20 
Adds removed placeholder pages/test and replaced them with working pages/test for Review Create, Edit, and Index
![image](https://user-images.githubusercontent.com/77415822/201439677-74430933-740f-4155-a37e-ca1882ca443f.png)

2022-11-13 00:25 UTC, tallyhawley commented
https://f22-5pm-1-team03-qa.herokuapp.com/
When trying to access your IndexPage, it just... breaks. And requires a reload for any page on the site to function. Looking at the console, it's a type error of some kind. 

<img width="914" alt="image" src="https://user-images.githubusercontent.com/20908336/201499856-4d687899-1850-4b9b-9ca9-f2f06219ed4d.png">

If you could fix this I'll merge it because it looks good otherwise

2022-11-13 17:34 UTC, ethanlee556 commented
> https://f22-5pm-1-team03-qa.herokuapp.com/ When trying to access your IndexPage, it just... breaks. And requires a reload for any page on the site to function. Looking at the console, it's a type error of some kind.
> 
> <img alt="image" width="914" src="https://user-images.githubusercontent.com/20908336/201499856-4d687899-1850-4b9b-9ca9-f2f06219ed4d.png">
> 
> If you could fix this I'll merge it because it looks good otherwise

Should work now

2022-11-14 02:48 UTC, tallyhawley reviewed
looks mostly good. please fix the URL routing errors & the item ID access issues

2022-11-14 02:48 UTC, tallyhawley commented on frontend/src/main/components/Review/ReviewTable.js
> +        }
on line 12 of this file - the url should say `review` not `reviews`. currently this does not match the existing routing.

2022-11-14 02:48 UTC, tallyhawley commented on frontend/src/main/components/Review/ReviewTable.js
> +        }
also, your itemID is not being accessed correctly. I think this should be `accessor: 'itemId'`, with a lowercase `d`. 
![image](https://user-images.githubusercontent.com/20908336/201563606-2ee56e2c-7b4b-4d20-a964-0ad814bb946b.png)

2022-11-14 02:48 UTC, tallyhawley commented on frontend/src/main/pages/Review/ReviewCreatePage.js
> +    return <Navigate to="/reviews/list" />
this should navigate to `/review/list`, not `/reviews/list`

2022-11-14 02:48 UTC, tallyhawley commented on frontend/src/main/pages/Review/ReviewEditPage.js
> +      itemID: review.itemID,
should be `itemId: review.itemId`. the only case where this should say `itemID` (with capital D) is on the column header. not when you're accessing the actual parameter.

2022-11-14 02:48 UTC, tallyhawley commented on frontend/src/main/pages/Review/ReviewEditPage.js
> +    return <Navigate to="/reviews/list" />
`/review/list`

2022-11-14 02:48 UTC, tallyhawley commented on frontend/src/main/pages/Review/ReviewCreatePage.js
> +      itemID: review.itemID,
`itemId: review.itemId`

this is causing issues with communicating between frontend and backend.

2022-11-14 04:57 UTC, ethanlee556 commented
![image](https://user-images.githubusercontent.com/77415822/201578530-02419724-61bf-4e65-900d-f794ba621461.png)
The itemID shows up now

2022-11-14 05:28 UTC, tallyhawley requested changes
could you update the tests so that they pass? should just be related to the itemId & /review/ vs /reviews/ changes

2022-11-14 07:22 UTC, ethanlee556 commented
Mutation Test Coverage:
![image](https://user-images.githubusercontent.com/77415822/201598973-00358e1f-c3a8-45d8-befb-3f0c6c743935.png)
![image](https://user-images.githubusercontent.com/77415822/201599008-fd873763-e562-421f-a3b7-7fdb8d6acd1a.png)

2022-11-14 08:27 UTC, tallyhawley approved these changes
lgtm!

2022-11-14 08:27 UTC, merged